### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Godspeeed1** [Jouca/BadgesAPI#2]
![image](https://github.com/user-attachments/assets/11c25936-d0f3-4c32-aabd-24940f8a66d4)

hey first time using github, probably the wrong place to ask for this and if it is then I am sorry, but please for the LOVE OF GODDDD, TELL. ME. WHAT THIS TEXTURE PACK IS! Its BEAUTIFUL!! I WANT IT, thank you <3 <3

**Comment by Jouca** [comment]
This is a mod called CustomProfiles that is handling the colors for popup, not a texture pack.

Yea, also use this kind place in GitHub for reports/suggest related to the project and not for another one, should help you to give you more context on what GitHub is.
